// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8gItbftikRmlWbS6RIRO4iyzNTQYmLAU',
    appId: '1:84998917478:web:c6411bdaa4ecfa1b73cca7',
    messagingSenderId: '84998917478',
    projectId: 'eltzamati',
    authDomain: 'eltzamati.firebaseapp.com',
    storageBucket: 'eltzamati.firebasestorage.app',
    measurementId: 'G-L1GZX13Y4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBWsAchRargRwB7nflkatNASeYjmXQlFI',
    appId: '1:84998917478:android:ee17f70a54b4c92573cca7',
    messagingSenderId: '84998917478',
    projectId: 'eltzamati',
    storageBucket: 'eltzamati.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzbO_cR8ZdaLaR_0OP0JxCkJE391QDTrU',
    appId: '1:84998917478:ios:257b085f871f43d073cca7',
    messagingSenderId: '84998917478',
    projectId: 'eltzamati',
    storageBucket: 'eltzamati.firebasestorage.app',
    iosBundleId: 'com.example.loanManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzbO_cR8ZdaLaR_0OP0JxCkJE391QDTrU',
    appId: '1:84998917478:ios:257b085f871f43d073cca7',
    messagingSenderId: '84998917478',
    projectId: 'eltzamati',
    storageBucket: 'eltzamati.firebasestorage.app',
    iosBundleId: 'com.example.loanManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8gItbftikRmlWbS6RIRO4iyzNTQYmLAU',
    appId: '1:84998917478:web:3ded95cc5149efcd73cca7',
    messagingSenderId: '84998917478',
    projectId: 'eltzamati',
    authDomain: 'eltzamati.firebaseapp.com',
    storageBucket: 'eltzamati.firebasestorage.app',
    measurementId: 'G-CPK38DMKHY',
  );
}
